---
- name: Playbook de test tout con
  hosts: jenkins
  become: yes
  gather_facts: no

  tasks:
    - name: Ping du serveur
      ping:

    - name: Afficher uname -a
      command: uname -a
      register: uname_out

    - name: Afficher la sortie de uname
      debug:
        msg: "{{ uname_out.stdout }}"

    - name: Cr√©er un fichier de test
      file:
        path: /tmp/ansible_ok.txt
        state: touch
